/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package network;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.apache.thrift.*;
import org.apache.thrift.async.*;
import org.apache.thrift.meta_data.*;
import org.apache.thrift.transport.*;
import org.apache.thrift.protocol.*;

public class TBall implements TBase<TBall, TBall._Fields>, java.io.Serializable, Cloneable {
  private static final TStruct STRUCT_DESC = new TStruct("TBall");

  private static final TField POSITIONS_FIELD_DESC = new TField("positions", TType.LIST, (short)1);
  private static final TField STORE_FIELD_DESC = new TField("store", TType.STRUCT, (short)2);
  private static final TField PLAYER_FIELD_DESC = new TField("player", TType.I32, (short)3);
  private static final TField ID_FIELD_DESC = new TField("id", TType.I32, (short)4);
  private static final TField ANGLE_FIELD_DESC = new TField("angle", TType.DOUBLE, (short)5);

  public List<TPosition> positions;
  public TPower store;
  /**
   * 
   * @see TPlayer
   */
  public TPlayer player;
  public int id;
  public double angle;

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements TFieldIdEnum {
    POSITIONS((short)1, "positions"),
    STORE((short)2, "store"),
    /**
     * 
     * @see TPlayer
     */
    PLAYER((short)3, "player"),
    ID((short)4, "id"),
    ANGLE((short)5, "angle");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // POSITIONS
          return POSITIONS;
        case 2: // STORE
          return STORE;
        case 3: // PLAYER
          return PLAYER;
        case 4: // ID
          return ID;
        case 5: // ANGLE
          return ANGLE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ID_ISSET_ID = 0;
  private static final int __ANGLE_ISSET_ID = 1;
  private BitSet __isset_bit_vector = new BitSet(2);

  public static final Map<_Fields, FieldMetaData> metaDataMap;
  static {
    Map<_Fields, FieldMetaData> tmpMap = new EnumMap<_Fields, FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.POSITIONS, new FieldMetaData("positions", TFieldRequirementType.DEFAULT, 
        new ListMetaData(TType.LIST, 
            new StructMetaData(TType.STRUCT, TPosition.class))));
    tmpMap.put(_Fields.STORE, new FieldMetaData("store", TFieldRequirementType.DEFAULT, 
        new StructMetaData(TType.STRUCT, TPower.class)));
    tmpMap.put(_Fields.PLAYER, new FieldMetaData("player", TFieldRequirementType.DEFAULT, 
        new EnumMetaData(TType.ENUM, TPlayer.class)));
    tmpMap.put(_Fields.ID, new FieldMetaData("id", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.I32)));
    tmpMap.put(_Fields.ANGLE, new FieldMetaData("angle", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.DOUBLE)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    FieldMetaData.addStructMetaDataMap(TBall.class, metaDataMap);
  }

  public TBall() {
  }

  public TBall(
    List<TPosition> positions,
    TPower store,
    TPlayer player,
    int id,
    double angle)
  {
    this();
    this.positions = positions;
    this.store = store;
    this.player = player;
    this.id = id;
    setIdIsSet(true);
    this.angle = angle;
    setAngleIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TBall(TBall other) {
    __isset_bit_vector.clear();
    __isset_bit_vector.or(other.__isset_bit_vector);
    if (other.isSetPositions()) {
      List<TPosition> __this__positions = new ArrayList<TPosition>();
      for (TPosition other_element : other.positions) {
        __this__positions.add(new TPosition(other_element));
      }
      this.positions = __this__positions;
    }
    if (other.isSetStore()) {
      this.store = new TPower(other.store);
    }
    if (other.isSetPlayer()) {
      this.player = other.player;
    }
    this.id = other.id;
    this.angle = other.angle;
  }

  public TBall deepCopy() {
    return new TBall(this);
  }

  @Override
  public void clear() {
    this.positions = null;
    this.store = null;
    this.player = null;
    setIdIsSet(false);
    this.id = 0;
    setAngleIsSet(false);
    this.angle = 0.0;
  }

  public int getPositionsSize() {
    return (this.positions == null) ? 0 : this.positions.size();
  }

  public java.util.Iterator<TPosition> getPositionsIterator() {
    return (this.positions == null) ? null : this.positions.iterator();
  }

  public void addToPositions(TPosition elem) {
    if (this.positions == null) {
      this.positions = new ArrayList<TPosition>();
    }
    this.positions.add(elem);
  }

  public List<TPosition> getPositions() {
    return this.positions;
  }

  public TBall setPositions(List<TPosition> positions) {
    this.positions = positions;
    return this;
  }

  public void unsetPositions() {
    this.positions = null;
  }

  /** Returns true if field positions is set (has been asigned a value) and false otherwise */
  public boolean isSetPositions() {
    return this.positions != null;
  }

  public void setPositionsIsSet(boolean value) {
    if (!value) {
      this.positions = null;
    }
  }

  public TPower getStore() {
    return this.store;
  }

  public TBall setStore(TPower store) {
    this.store = store;
    return this;
  }

  public void unsetStore() {
    this.store = null;
  }

  /** Returns true if field store is set (has been asigned a value) and false otherwise */
  public boolean isSetStore() {
    return this.store != null;
  }

  public void setStoreIsSet(boolean value) {
    if (!value) {
      this.store = null;
    }
  }

  /**
   * 
   * @see TPlayer
   */
  public TPlayer getPlayer() {
    return this.player;
  }

  /**
   * 
   * @see TPlayer
   */
  public TBall setPlayer(TPlayer player) {
    this.player = player;
    return this;
  }

  public void unsetPlayer() {
    this.player = null;
  }

  /** Returns true if field player is set (has been asigned a value) and false otherwise */
  public boolean isSetPlayer() {
    return this.player != null;
  }

  public void setPlayerIsSet(boolean value) {
    if (!value) {
      this.player = null;
    }
  }

  public int getId() {
    return this.id;
  }

  public TBall setId(int id) {
    this.id = id;
    setIdIsSet(true);
    return this;
  }

  public void unsetId() {
    __isset_bit_vector.clear(__ID_ISSET_ID);
  }

  /** Returns true if field id is set (has been asigned a value) and false otherwise */
  public boolean isSetId() {
    return __isset_bit_vector.get(__ID_ISSET_ID);
  }

  public void setIdIsSet(boolean value) {
    __isset_bit_vector.set(__ID_ISSET_ID, value);
  }

  public double getAngle() {
    return this.angle;
  }

  public TBall setAngle(double angle) {
    this.angle = angle;
    setAngleIsSet(true);
    return this;
  }

  public void unsetAngle() {
    __isset_bit_vector.clear(__ANGLE_ISSET_ID);
  }

  /** Returns true if field angle is set (has been asigned a value) and false otherwise */
  public boolean isSetAngle() {
    return __isset_bit_vector.get(__ANGLE_ISSET_ID);
  }

  public void setAngleIsSet(boolean value) {
    __isset_bit_vector.set(__ANGLE_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case POSITIONS:
      if (value == null) {
        unsetPositions();
      } else {
        setPositions((List<TPosition>)value);
      }
      break;

    case STORE:
      if (value == null) {
        unsetStore();
      } else {
        setStore((TPower)value);
      }
      break;

    case PLAYER:
      if (value == null) {
        unsetPlayer();
      } else {
        setPlayer((TPlayer)value);
      }
      break;

    case ID:
      if (value == null) {
        unsetId();
      } else {
        setId((Integer)value);
      }
      break;

    case ANGLE:
      if (value == null) {
        unsetAngle();
      } else {
        setAngle((Double)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case POSITIONS:
      return getPositions();

    case STORE:
      return getStore();

    case PLAYER:
      return getPlayer();

    case ID:
      return new Integer(getId());

    case ANGLE:
      return new Double(getAngle());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been asigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case POSITIONS:
      return isSetPositions();
    case STORE:
      return isSetStore();
    case PLAYER:
      return isSetPlayer();
    case ID:
      return isSetId();
    case ANGLE:
      return isSetAngle();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TBall)
      return this.equals((TBall)that);
    return false;
  }

  public boolean equals(TBall that) {
    if (that == null)
      return false;

    boolean this_present_positions = true && this.isSetPositions();
    boolean that_present_positions = true && that.isSetPositions();
    if (this_present_positions || that_present_positions) {
      if (!(this_present_positions && that_present_positions))
        return false;
      if (!this.positions.equals(that.positions))
        return false;
    }

    boolean this_present_store = true && this.isSetStore();
    boolean that_present_store = true && that.isSetStore();
    if (this_present_store || that_present_store) {
      if (!(this_present_store && that_present_store))
        return false;
      if (!this.store.equals(that.store))
        return false;
    }

    boolean this_present_player = true && this.isSetPlayer();
    boolean that_present_player = true && that.isSetPlayer();
    if (this_present_player || that_present_player) {
      if (!(this_present_player && that_present_player))
        return false;
      if (!this.player.equals(that.player))
        return false;
    }

    boolean this_present_id = true;
    boolean that_present_id = true;
    if (this_present_id || that_present_id) {
      if (!(this_present_id && that_present_id))
        return false;
      if (this.id != that.id)
        return false;
    }

    boolean this_present_angle = true;
    boolean that_present_angle = true;
    if (this_present_angle || that_present_angle) {
      if (!(this_present_angle && that_present_angle))
        return false;
      if (this.angle != that.angle)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(TBall other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    TBall typedOther = (TBall)other;

    lastComparison = Boolean.valueOf(isSetPositions()).compareTo(typedOther.isSetPositions());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPositions()) {
      lastComparison = TBaseHelper.compareTo(this.positions, typedOther.positions);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetStore()).compareTo(typedOther.isSetStore());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStore()) {
      lastComparison = TBaseHelper.compareTo(this.store, typedOther.store);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPlayer()).compareTo(typedOther.isSetPlayer());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPlayer()) {
      lastComparison = TBaseHelper.compareTo(this.player, typedOther.player);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetId()).compareTo(typedOther.isSetId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetId()) {
      lastComparison = TBaseHelper.compareTo(this.id, typedOther.id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetAngle()).compareTo(typedOther.isSetAngle());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAngle()) {
      lastComparison = TBaseHelper.compareTo(this.angle, typedOther.angle);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(TProtocol iprot) throws TException {
    TField field;
    iprot.readStructBegin();
    while (true)
    {
      field = iprot.readFieldBegin();
      if (field.type == TType.STOP) { 
        break;
      }
      switch (field.id) {
        case 1: // POSITIONS
          if (field.type == TType.LIST) {
            {
              TList _list0 = iprot.readListBegin();
              this.positions = new ArrayList<TPosition>(_list0.size);
              for (int _i1 = 0; _i1 < _list0.size; ++_i1)
              {
                TPosition _elem2;
                _elem2 = new TPosition();
                _elem2.read(iprot);
                this.positions.add(_elem2);
              }
              iprot.readListEnd();
            }
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 2: // STORE
          if (field.type == TType.STRUCT) {
            this.store = new TPower();
            this.store.read(iprot);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 3: // PLAYER
          if (field.type == TType.I32) {
            this.player = TPlayer.findByValue(iprot.readI32());
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 4: // ID
          if (field.type == TType.I32) {
            this.id = iprot.readI32();
            setIdIsSet(true);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 5: // ANGLE
          if (field.type == TType.DOUBLE) {
            this.angle = iprot.readDouble();
            setAngleIsSet(true);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          TProtocolUtil.skip(iprot, field.type);
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();

    // check for required fields of primitive type, which can't be checked in the validate method
    validate();
  }

  public void write(TProtocol oprot) throws TException {
    validate();

    oprot.writeStructBegin(STRUCT_DESC);
    if (this.positions != null) {
      oprot.writeFieldBegin(POSITIONS_FIELD_DESC);
      {
        oprot.writeListBegin(new TList(TType.STRUCT, this.positions.size()));
        for (TPosition _iter3 : this.positions)
        {
          _iter3.write(oprot);
        }
        oprot.writeListEnd();
      }
      oprot.writeFieldEnd();
    }
    if (this.store != null) {
      oprot.writeFieldBegin(STORE_FIELD_DESC);
      this.store.write(oprot);
      oprot.writeFieldEnd();
    }
    if (this.player != null) {
      oprot.writeFieldBegin(PLAYER_FIELD_DESC);
      oprot.writeI32(this.player.getValue());
      oprot.writeFieldEnd();
    }
    oprot.writeFieldBegin(ID_FIELD_DESC);
    oprot.writeI32(this.id);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(ANGLE_FIELD_DESC);
    oprot.writeDouble(this.angle);
    oprot.writeFieldEnd();
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TBall(");
    boolean first = true;

    sb.append("positions:");
    if (this.positions == null) {
      sb.append("null");
    } else {
      sb.append(this.positions);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("store:");
    if (this.store == null) {
      sb.append("null");
    } else {
      sb.append(this.store);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("player:");
    if (this.player == null) {
      sb.append("null");
    } else {
      sb.append(this.player);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("id:");
    sb.append(this.id);
    first = false;
    if (!first) sb.append(", ");
    sb.append("angle:");
    sb.append(this.angle);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws TException {
    // check for required fields
  }

}

