/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package network;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TDirection implements TEnum {
  NONE(0),
  RIGHT(1),
  LEFT(2);

  private final int value;

  private TDirection(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TDirection findByValue(int value) { 
    switch (value) {
      case 0:
        return NONE;
      case 1:
        return RIGHT;
      case 2:
        return LEFT;
      default:
        return null;
    }
  }
}
