/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package network;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TPowerUp implements TEnum {
  NONE(0),
  SPEED(1),
  INVIS(2),
  STUN(3),
  STUNNED(4);

  private final int value;

  private TPowerUp(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TPowerUp findByValue(int value) { 
    switch (value) {
      case 0:
        return NONE;
      case 1:
        return SPEED;
      case 2:
        return INVIS;
      case 3:
        return STUN;
      case 4:
        return STUNNED;
      default:
        return null;
    }
  }
}
